sudo: required
services:
    - docker

before_install:
    - docker build -t jia2976/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run jia1976/react-test npm test -- --coverage

after_success:
    - docker build -t jia1976/multi-client ./client
    - docker build -t jia1976/multi-nginx ./nginx
    - docker build -t jia1976/multi-server ./server
    - docker build -t jia1976/multi-worker ./worker
    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push jia1976/multi-client
    - docker push jia1976/multi-nginx
    - docker push jia1976/multi-server
    - docker push jia1976/multi-worker


