language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jia1976/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jia1976/react-test npm test

after_success:
    - docker build -t jia1976/multi-client ./client
    - docker build -t jia1976/multi-nginx ./nginx
    - docker build -t jia1976/multi-server ./server
    - docker build -t jia1976/multi-worker ./worker
    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push jia1976/multi-client
    - docker push jia1976/multi-nginx
    - docker push jia1976/multi-server
    - docker push jia1976/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-174328686859
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY